# config/packages/security.yaml
security:
    # 1. La sección 'password_hashers' AHORA ESTÁ DENTRO de 'security:'
    password_hashers:
        # Aquí defines qué hasher usar para cada clase de usuario
        App\Entity\User: 'auto'
        # Si tuvieras otra entidad de usuario, la definirías aquí también
        # App\Entity\AnotherUser: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    firewalls:
        main:
            pattern: ^/
            # Se ELIMINA la línea 'anonymous: true' (ya corregido)
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_index
            logout:
                path: app_logout
                target: app_login
    
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/recovery, roles: PUBLIC_ACCESS }
        # Esto aplica a todas las rutas que no coincidan con las anteriores
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }